volumes:
  pg-admin:
    external: true
  accomplist:
    external: true
services:
  fastapi:
    environment:
      CORS_HOST: http://localhost:3000
      LOCAL_HOST: http://localhost:8000
      DATABASE_URL: postgresql://admin:password@database/accomplist
      SIGNING_KEY: ddcfb42d563bed0ec4f9e2290ddf2d80848472affd4b2dbc063aba5ceadd3745
      WAIT_HOSTS: database:5432
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60
      PORT: 8000
    build:
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
  database:
    image: postgres:14.5-bullseye
    volumes:
      - accomplist:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: accomplist
      SIGNING_KEY: ddcfb42d563bed0ec4f9e2290ddf2d80848472affd4b2dbc063aba5ceadd3745
    ports:
      - "15432:5432"

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_API_HOST: http://localhost:8000
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
      SIGNING_KEY: ddcfb42d563bed0ec4f9e2290ddf2d80848472affd4b2dbc063aba5ceadd3745
